openapi: 3.0.0
servers:
  - description: Localhost
    url: http://lolcahost:8080/api/products/1.0.0
info:
  description: AtSistemas Product prices challenge api
  version: "1.0.0"
  title: Products API
  contact:
    email: ardielfs@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: products
    description: Products operations
  - name: prices
    description: Products price operations
paths:
  /api/ecommerce/brands/{brand-id}/products/{product-id}/prices:
    get:
      tags:
        - prices
      summary: retrieve product price
      operationId: getProductPrice
      description: |
        Return the corresponding product price for the given date
      parameters:
        - in: path
          name: brand-id
          description: Brand identifier
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
          example: 1
        - in: path
          name: product-id
          description: Product identifier
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
          example: 35455
        - in: query
          name: date
          description: Product price application date
          required: true
          schema:
            type: string
            format: date-time
          example: 2020-06-14T10:00:00Z
      responses:
        '200':
          description: Product price for the given date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPriceDetail'
              examples:
                2020-06-14T10:00:00Z:
                  value:
                    productId: 35455
                    brandId: 1
                    tariffId: 1
                    tariffDateFrom: 2020-06-14T00:00:00Z
                    tariffDateTo: 2020-12-31T23:59:59Z
                    price: "35.50€"
                    priceValue: 35.5
                    currency: EUR
                2020-06-14T16:00:00Z:
                  value:
                    productId: 35455
                    brandId: 1
                    tariffId: 2
                    tariffDateFrom: 2020-06-14T15:00:00Z
                    tariffDateTo: 2020-06-14T18:30:00Z
                    price: "25.45€"
                    priceValue: 25.45
                    currency: EUR
                2020-06-14T21:00:00Z:
                  value:
                    productId: 35455
                    brandId: 1
                    tariffId: 1
                    tariffDateFrom: 2020-06-14T00:00:00Z
                    tariffDateTo: 2020-12-31T23:59:59Z
                    price: "35.50€"
                    priceValue: 35.5
                    currency: EUR
                2020-06-15T10:00:00Z:
                  value:
                    productId: 35455
                    brandId: 1
                    tariffId: 3
                    tariffDateFrom: 2020-06-15T00:00:00Z
                    tariffDateTo: 2020-06-15T11:00:00Z
                    price: "30.50€"
                    priceValue: 30.5
                    currency: EUR
                2020-06-16T21:00:00Z:
                  value:
                    productId: 35455
                    brandId: 1
                    tariffId: 4
                    tariffDateFrom: 2020-06-15T16:00:00
                    tariffDateTo: 2020-12-31T23:59:59Z
                    price: "38.95€"
                    priceValue: 38.95
                    currency: EUR
        '400':
          description: bad input parameter
        '404':
          $ref: '#/components/responses/NotFound'
components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    ProductPriceDetail:
      type: object
      required:
        - productId
        - brandId
        - tariffId
        - tariffDateFrom
        - tariffDateTo
        - price
      properties:
        productId:
          type: integer
          format: int64
          example: 35455
        brandId:
          type: integer
          format: int64
          example: 1
        tariffId:
          type: integer
          format: int64
          example: 1
        tariffDateFrom:
          type: string
          format: date-time
          example: '2020-06-14T00:00:00Z'
        tariffDateTo:
          type: string
          format: date-time
          example: '2020-12-31T23:59:59Z'
        price:
          type: string
          example: "35.50€"
        priceValue:
          type: number
          format: double
          example: 35.50
        currency:
          type: string
          enum:
            - EUR
    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
